### PR TITLE
Added raspberrypi modifications, allowing use with raspberrypi.

### PR DESCRIPTION
**Pull request by mwinters-stuff**
I dont have any of the esp devices, but plenty of rasbperry pi's as I suspect many others do. I wanted to try the experiments so changed the code to run on a raspberry pi. Provided as a separate directory to the main one.

### CODE REVIEW

**Comment by watadarkstar** [comment]
That's pretty useful @wintersandroid could you provide some more details. Did you get this working on a raspberry pi and if so which model and what was your wire to pin setup? 🥇

**Comment by mwinters-stuff** [comment]
Hi. It worked on the old rpi model B upwards. I mentioned pin numbers that I had configured the servo driver but that is totally configurable by the user.

I had forgotten about this - have some esp8266 devices now.

**Comment by abhinuvpitale** [comment]
I am interested in using this, is this PR still active or going to be merged? I think its pretty useful.

**Comment by abhinuvpitale** [comment]
Getting this error when trying to recreate your steps from the README.md @mwinters-stuff 

```
Credentials.h:24:7: error: ‘String’ does not name a type
 const String SignalID = "rocket-man";
       ^~~~~~
Credentials.h:27:7: error: ‘String’ does not name a type
 const String DarkSkyAPIKey = "YOUR_DARK_SKY_API_KEY";
       ^~~~~~
Credentials.h:28:7: error: ‘String’ does not name a type
 const String GeoCodingAPiKey = "YOUR_GEOCODING_API_KEY";
       ^~~~~~
Credentials.h:31:7: error: ‘String’ does not name a type
 const String BarChartAPIKey = "YOUR_BAR_CHART_API_KEY";
       ^~~~~~
make[1]: *** [build/debug/obj/RaspberryPiSignals.o] Error 1
make: *** [RaspberryPiSignals] Error 2
```

**Comment by mwinters-stuff** [comment]
@abhinuvpitale I have not looked at this since I did it, maybe the string type needs changing or Rpi, probably std::string

**Comment by abhinuvpitale** [comment]
Gotcha

**Pull request closed without merging**
